### ISSUE TITLE
Failing to download response body

### ISSUE THREAD

**Issue by JPHaus** [robsideshow/mbta-bustracker#108]
In `dictChecker.py` it appears that the response no longer includes the header 'content-length' and it's causing the error.

Traceback:
```python
Traceback (most recent call last):
  File "dictChecker.py", line 78, in <module>
    download_response_body(response, "data")
  File "dictChecker.py", line 38, in download_response_body
    byte_length = float(response.headers['content-length'])
  File "C:\Users\jp\AppData\Local\Continuum\anaconda3\envs\Python36\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```

Printing the response headers I can see that there is indeed no 'content-length':
```python
{'Server': 'AmazonS3', 'ETag': '"3842a1ecc0a89d2f1300ddfef9de1fe1-2"', 'Age': '374', 'X-Cache': 'Hit from cloudfront', 'Date': 'Wed, 24 Oct 2018 19:02:24 GMT', 'Via': '1.1 796000a2aeb611d2a2225763c567f35d.cloudfront.net (CloudFront)', 'Connection': 'keep-alive', 'X-Amz-Cf-Id': 'TE2l0JtI_y8Ti671fCMYiWjrNYrO_jU17iGHqbU9UZTBmE34Q8K3Sw=='}
```

**Comment by robsideshow** [comment]
Thanks Jonathan!  Trying the URL just now, these are the response headers I see:
`{'Content-Length': '16146018', 'Via': '1.1 92e459346829b56068b240340d6508a6.cloudfront.net (CloudFront)', 'X-Cache': 'Miss from cloudfront', 'Accept-Ranges': 'bytes', 'Server': 'AmazonS3', 'Last-Modified': 'Thu, 25 Oct 2018 14:35:48 GMT', 'Connection': 'keep-alive', 'ETag': '"88ba7b8b98500a41583b172d82eec541-2"', 'X-Amz-Cf-Id': 'j7FSCEV_V0-Ya7duRYyxIdtEaetBgbjNrqtiEw0RFoK8EgawLoaI1A==', 'Date': 'Thu, 25 Oct 2018 21:36:02 GMT', 'Content-Type': 'application/zip'}`

With 'Content-Length' included.  I believe the case difference is not a problem (the keys are hit with the `.lower()` method).  Nonetheless, we should not trust third-parties to have all the fields they usually have, so I shall make the code more robust.  Thanks again for filing the issue and Welcome!
