### ISSUE TITLE
Click on a stop, show routes passing that stop

### ISSUE THREAD

**Issue by Shanfan** [robsideshow/mbta-bustracker#20]

**Comment by bdougsand** [comment]
Should we consider this closed? Right now, users can see information in the popup about the routes _with predictions available_. Is this enough, or should we actually show all routes, whether there are vehicles predicted or not? If we show all routes, how should we indicate that some routes have no predictions available?

**Comment by robsideshow** [comment]
I think we can consider it closed.  We could discuss adding the routes with no predictions, presumably grayed out.  Maybe if the user clicks the grayed route, we flash a message saying no predictions.
