### ISSUE TITLE
Toggle on/off All Routes?

### ISSUE THREAD

**Issue by Shanfan** [robsideshow/mbta-bustracker#31]
What about:
- Toggle everything
- Toggle all Rapid Transit
- Toggle all Buses

Anything else?

**Comment by bdougsand** [comment]
This is easy to implement, and it'll be a good stress test for both the front and back end. If it performs reasonably well and doesn't look appalling, it could also be a good thing to demo.

But apart from its value as a stress test and demo, I don't see this as being particularly useful. This could be an "advanced settings" type feature.

**Comment by Shanfan** [comment]
Agreed.
Toggle All is not something for the daily commuters. It's for those commuters who at times feel like a commander of the MBTA troop.
