### ISSUE TITLE
Design the selected vehicle marker

### ISSUE THREAD

**Issue by bdougsand** [robsideshow/mbta-bustracker#32]
At the very least, a selected vehicle's marker should look distinct from the others. We might also consider drawing a line from the info box to the selected marker.

**Comment by robsideshow** [comment]
Is there going to be an info box?  I thought we said that when you click on a vehicle, the predictions for each stop pop up at the stops, instead of an info box.

**Comment by bdougsand** [comment]
Yes, I'll tackle the stop pop-ups tonight, but I'm not sure if that removes the usefulness of the info box. I'm imagining it as the place where we put information about the current selection, whether that's a vehicle or a route or something else.

**Comment by Shanfan** [comment]
I think the pointer of the popup can be sharper. That'll make it look pointier.
As for indicating the selected vehicle, we could reverse the color of the icon: The route color as the background, and white for the text color.

![image](https://cloud.githubusercontent.com/assets/869370/13801587/aa65a276-eb09-11e5-8f4f-66077b2991be.png)
