### ISSUE TITLE
Expose stop predictions in UI

### ISSUE THREAD

**Issue by bdougsand** [robsideshow/mbta-bustracker#37]

**Comment by Shanfan** [comment]
what is the information to show here?
- Estimated time to arrival at a particular stop? -- This will need user input: a given vehicle and a given stop, right?

**Comment by bdougsand** [comment]
To clarify, I meant the predictions the user gets when s/he clicks on a stop. So: ETAs for the next few vehicles to arrive at that stop.

**Comment by bdougsand** [comment]
But you raise a good question. What happens if the user selects a stop and a vehicle? Does selecting a stop clear the vehicle selection? And vice versa?

**Comment by Shanfan** [comment]
Quick sketch:
- Clicking on a stop, show an Inbound or Outbound toggle, then show the next X vehicles coming to this stop. There's also a "Show Nearby" button.
- Clicking on the "Show Nearby" button, it can show the nearby stops and routes that are coming through. But I haven't fleshed this out. Take it as a "Maybe". 

![image](https://cloud.githubusercontent.com/assets/869370/13802277/a1c4f07a-eb10-11e5-9cb9-116a9dd81429.png)

Ideally as soon as the user clicks outside of the popup, it should disappear.
I see somewhere we have the implementation of an "X" button on top right to close the popup. I don't have strong preference. Just thought it's gonna be annoying if I had multiple popups and had to close them one by one.

**Comment by Shanfan** [comment]
Btw, I put 2 popups at the same time for the convenience of illustration.
I think ideally it should just show one popup at a time. As soon as the user clicks outside of the popup, it should disappear.

I see somewhere we have the implementation of an "X" button on top right to close the popup. I don't have strong preference. Just thought it's gonna be annoying if I had multiple popups and had to close them one by one.

**Comment by Shanfan** [comment]
Should we consider the design done, and treat this one as an implementation issue?
