### ISSUE TITLE
Should show route name at bottom of stop predictions popup, not route_id.  For example, currently shows "747" but we want it to show "CT2".

### ISSUE THREAD

**Issue by robsideshow** [robsideshow/mbta-bustracker#50]

**Comment by bdougsand** [comment]
Only the route ids are available for routes that have not been loaded. Should we generate a JavaScript file that has a dictionary of route_ids -> route_names?

**Comment by robsideshow** [comment]
When the app starts, a dictionary of `route_id : route name` is passed in to the liveMap.html as `routeTitles`.  That, I believe, is how all the route names are displayed in the toggle box, rather than route_ids.
Is that dictionary not available to the javascript?
