### ISSUE TITLE
Parent stops do not work correctly when loaded via /api/rectangle

### ISSUE THREAD

**Issue by bdougsand** [robsideshow/mbta-bustracker#63]
I'll have to investigate, but I think this is purely a client-side issue. The client should be able to get all the information it needs from the results of `/api/rectangle`.

**Comment by robsideshow** [comment]
Not sure whether this could be part of the issue but there is a slight difference in what you get from `rectangle` vs what you get from `routeinfo`:
a) from `rectangle`, you get a single list, called `stops`, which contains both regular stops and parent stops. 
b) from `routeinfo`, you get two separate lists: one called `stops` containing ONLY regular stops, and a second called `parent_stops` containing the parent stops for all child stops in `stops`
Let me know if you want to get the info from `rectangle` differently.
