### ISSUE TITLE
Include "direction" property for stops with only one associated direction

### ISSUE THREAD

**Issue by bdougsand** [robsideshow/mbta-bustracker#66]
Many bus stops only have routes going in one direction. If this property is added to the response in `api/routeinfo`, the client can show the toggle switch only when it is relevant to a stop.

**Comment by robsideshow** [comment]
What would be best?  Directions are currently either '0' or '1' (strings) for a given shape.  Do you want a list of the directions?  ['0'] or ['1'] or ['0','1']
Or a single string? '0' or '1' or '10' (or 'both')?

**Comment by bdougsand** [comment]
I was thinking that it would only be on stops that have a single direction, and that it would be a string. If you don't want to do that, I think the array of strings is the second best option.
