### ISSUE TITLE
Top Nav goes hidden at certain map zoom level

### ISSUE THREAD

**Issue by Shanfan** [robsideshow/mbta-bustracker#7]
I can see the top nav when I first land on the page. But once I zoom in on the map, the top nav rolls up and I'm not able to pull it down even if I zoom the map back to the starting level.

**Comment by Shanfan** [comment]
This seems to only happen in Chrome. It looks all right in Safari.

**Comment by robsideshow** [comment]
Also happens in Explorer.  In both Chrome and IE, it only happens when clicking the zoom buttons in the upper left corner, NOT when using the mouse scroll wheel (which is how I always zoom so I never noticed it before now).

**Comment by Shanfan** [comment]
It looks like before clicking the "+/-" to zoom the map, the bottom area of the map (marked with "leaflet") is cut off.
Once "+/-" is clicked, the bottom stripe will appear, hence pushing the nav bar upward, and it becomes unable to scroll back.
Clicking on the "locate me" button - which does nothing but collects a mouse event - would pull the nav bar back down.
![image](https://cloud.githubusercontent.com/assets/869370/13835993/8d389238-ebd3-11e5-9f94-811ef0084f6a.png)
